version: 2
jobs:
  test-centos-7:
    working_directory: ~/ansible-os-hardening
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install and run ssh service on target
          command: apt-get install openssh && service openssh restart    
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install test-kitchen
          command: bundle install
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test os-centos7-ansible-latest
  test-ubuntu-trusty:
    working_directory: ~/ansible-os-hardening
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install and run ssh service on target
          command: sudo apt-get install openssh && service openssh restart 
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install test-kitchen
          command: bundle install
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test os-ubuntu1404-ansible-latest
workflows:
  version: 2
  build:
    jobs:
      - test-centos-7
      - test-ubuntu-trusty